### PR TITLE
Download vch cert

### LINKED ISSUE #159: The UI does not allow a user to download the server certificate for a VCH
**VIC version:**

1.3.0 RC2

**Steps to reproduce:**

Deploy a VCH using the VCH Creation Wizard, leaving TLS enabled.

**Actual behavior:**

There is no way to download the server certificate via the UI.

**Expected behavior:**

An action or link is present on the resulting VCH that allows the user to download the server certificate.

**Additional details as necessary:**

The server certificate can be downloaded like logs, except from `/certificate` instead of `/logs`.

@lweitzman: This may need UX work; I don't see it in the mockups. (Alternatively, maybe it's there in both the mockups and the UI, but I'm not seeing it.)

### PR DESCRIPTION
**Pull request by jak-atx**
Fixes #159

### CODE REVIEW

File: h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts [hunk 1]
```diff
@@ -225,6 +231,50 @@ export class VicVchViewComponent implements OnInit, OnDestroy {
     this.vmViewService.getContainersData({}); // TODO: filter containers for the vch
   }
 
+   /**
+   * Download Certificate for VCH
+   */
+  downloadVchCert(vch: VirtualContainerHost) {
+    this.isDgLoading = true;
```
Comment (zjs) [inline h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts]: Does this function actually have an impact on the datagrid? It doesn't seem like it should; we write the hidden anchor to the end of the body.

File: h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts [hunk 2]
```diff
@@ -225,6 +231,50 @@ export class VicVchViewComponent implements OnInit, OnDestroy {
...
+      this.createWzService.getVicApplianceIp(),
+      this.createWzService.acquireCloneTicket()
+    ).catch(err => {
+      return Observable.throw(err);
+    }).subscribe(([serviceHost, cloneTicket]) => {
+      const vchId = vch.id.split(':')[3];
+      const servicePort = VIC_APPLIANCE_PORT;
+      const targetHost = this.extSessionService.getVcenterServersInfo()[0];
+      const targetHostname = targetHost.name;
+      const targetThumbprint = targetHost.thumbprint;
```
Comment (zjs) [inline h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts]: Not a blocker for 1.3.0, but... can we file an issue to clean this up after?

It seems like the code here is duplicated in at least two other places already:
```
     const vchId = vch.id.split(':')[3];
     const servicePort = VIC_APPLIANCE_PORT;
     const targetHost = this.extSessionService.getVcenterServersInfo()[0];
     const targetHostname = targetHost.name;
     const targetThumbprint = targetHost.thumbprint; 
```

Having a central place where we construct URLs for making requests to the API in a consistent way should both simplify things and reduce fragility (which will be important as we haven't committed to maintaining backwards-compatibility with the current API in future releases).

File: h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts [hunk 3]
```diff
@@ -225,6 +231,50 @@ export class VicVchViewComponent implements OnInit, OnDestroy {
...
+      const url =
+        `https://${serviceHost}:${servicePort}/container/target/${targetHostname}/vch/${vchId}/certificate?thumbprint=${targetThumbprint}`;
+
+      const headers  = new Headers({
+        'Content-Type': 'application/json',
+        'X-VMWARE-TICKET': cloneTicket
+      });
+
+      const options  = new RequestOptions({ headers: headers });
```
Comment (zjs) [inline h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts]: Also not a blocker for 1.3.0.

We should consolidate the code for constructing requests options as well.

**Comment by jak-atx** [comment]
Yes. There is some refactoring that needs to happen here I am aware of. This code is very similar to delete and we will plan to factor that out into a consolidated service.

File: h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts (hunk 1 above)
Comment (jak-atx) [reply h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts]: Yes, isDgLoading is something we check on the grid. So it would launch the spinner over the grid while the download happens. But has nothing to do with the anchor itself.

File: h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts (hunk 2 above)
Comment (jak-atx) [reply h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts]: Agreed. Will create a refactoring issue for these repetitive functions.

**Comment by jak-atx** [comment]
https://github.com/vmware/vic-ui/issues/171 to track post 1.3 refactoring.

File: h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html [hunk 4]
```diff
@@ -50,6 +50,7 @@
   <clr-dg-row *ngFor="let item of vchs">
     <clr-dg-action-overflow class="{{item.name}}">
       <button class="action-item {{item.name}}" (click)="deleteVch(item)">Delete</button>
+      <button class="action-item cert {{item.name}}" (click)="vchCert(item)">Download VCH certificate</button>
```
Comment (jooskim) [inline h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html]: Function `vchCert` does not exist on the VicVchViewComponent and it breaks the application.

**Comment by jak-atx** [comment]
Updated.

File: h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html [hunk 5]
```diff
@@ -50,6 +50,7 @@
   <clr-dg-row *ngFor="let item of vchs">
     <clr-dg-action-overflow class="{{item.name}}">
       <button class="action-item {{item.name}}" (click)="deleteVch(item)">Delete</button>
+      <button class="action-item cert {{item.name}}" (click)="downloadVchCert(item)">Download VCH certificate</button>
```
Comment (jooskim) [inline h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html]: This is not a major issue but potentially makes our tests brittle. Since now have more than one button element with the same class (which basically is the VCH name), you need to be aware that altering the order of these buttons will break the E2E tests. See the attached snippet below:

https://github.com/vmware/vic-ui/blob/master/h5c/vic/src/vic-webapp/e2e/app.po.ts#L147

I suggest you add a class to it just like you did for downloadVchCert.

Comment (jooskim) [reply h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html]: To give an extra context, the default behavior of `clickByCSS()`, as you wrote, will pick up whatever is found first if multiple instances are found.

File: h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts [hunk 6]
```diff
@@ -225,6 +231,50 @@ export class VicVchViewComponent implements OnInit, OnDestroy {
...
+   */
+  downloadVchCert(vch: VirtualContainerHost) {
+    this.isDgLoading = true;
+    Observable.combineLatest(
+      this.createWzService.getVicApplianceIp(),
+      this.createWzService.acquireCloneTicket()
+    ).catch(err => {
+      return Observable.throw(err);
+    }).subscribe(([serviceHost, cloneTicket]) => {
+      const vchId = vch.id.split(':')[3];
```
Comment (jooskim) [inline h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts]: Could we use `vch.name` inststead of `vch.id` for the pem file name? It would be easier for users to realize which pem file is for which VCH. MOID is rather for internal referencing purposes.

File: h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts [hunk 7]
```diff
@@ -225,6 +231,50 @@ export class VicVchViewComponent implements OnInit, OnDestroy {
...
+
+      const options  = new RequestOptions({ headers: headers });
+      this.http.get(url, options)
+        .map(response => response.text())
+        .subscribe(response => {
+          const uriContent = 'data:application/octet-stream,' + encodeURIComponent(response);
+          const link = document.createElement('a');
+          document.body.appendChild(link);
+          link.setAttribute('type', 'hidden');
+          link.download = vch.name + '-certificate.pem';
```
Comment (jak-atx) [inline h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.component.ts]: now using vch name rather than id

**Comment by jak-atx** [comment]
Updated to make tests more stable and changed vch id to name for pem file

**Comment by jooskim** [comment]
LGTM.
